name: "Sort"

on:
  workflow_dispatch:
  schedule:
    # Every 3 hours
    - cron: "0 18 * * *"

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
          echo "token: ${{ secrets.TODOIST_TOKEN }}" > config.yml
          python -m pip install --upgrade pip pipenv
          make init
          make sort
        env:
          TZ: "Asia/Tokyo"

      - uses: rjstone/discord-webhook-notify@v1
        if: "! success()"
        with:
          description: "⚠ Sorting daily tasks failed!"
          severity: error
          avatarUrl: https://www.suruga-ya.jp/database/pics_light/game/871005085.jpg
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - uses: rjstone/discord-webhook-notify@v1
        if: "success()"
        with:
          description: "✅ Sorting daily tasks finished!"
          severity: info
          avatarUrl: https://www.suruga-ya.jp/database/pics_light/game/871005085.jpg
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
