name: "Sort"

on:
  schedule:
    # Every 22 hours
    - cron: '0 13 * * *'

jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: |
          echo "token: ${{ secrets.TODOIST_TOKEN }}" > config.yml
          python -m pip install --upgrade pip pipenv
          make init
          make sort
        env:
          TZ: 'Asia/Tokyo'

